### ISSUE TITLE
SBML import

### ISSUE THREAD

**Issue by SiFTW** [SciML/ReactionNetworkImporters.jl#16]
Being able to import SBML would be highly enabling for me to switch Julia.

**Comment by isaacsas** [comment]
Direct SBML import would be great, but SBML is a beast. This has been an open DEBio issue for several years, but no one has had the time to invest in it yet unfortunately. I suspect this won't happen until there are dedicated funds to hire a programmer to implement it.

In the meantime you can either directly call the Python SBML API using PyCall, or you could try using Bionetgen to generate a .net file from your SBML model. Depending on the features you need it might work with ReactionNetworkImporters, and if it doesn't work out of the box I'd be happy to try to see if I can get them added in. Right now we have successfully loaded several (large) published Bionetgen-based models in DEBio through this approach.

**Comment by ChrisRackauckas** [comment]
It might be nice to handle it by using a PyCall to an SBML parser and then directly using the parsed version. That shouldn't be too bad.

**Comment by VitaminBrad** [comment]
I've done something like this, Chris... If the intention is to run scientific machine learning on the equations from an SBML file, this is my current solution:

- Within Python, use libSBML to extract a string for every differential equation
- Use regex and an indexed dataframe to convert each of the species references into u[i]s.
- In Julia, Meta.parse() each line to turn them into expressions
- du[:] = .eval(u[:]) at each timestep.

I may be able to contribute this code, in a reliable generalized version, by the end of this year. Is there someone already working on something like this?

**Comment by ChrisRackauckas** [comment]
It would be nice to see that in order to use it as a starting point, even if it's just a work in progress. I know that @giordano was looking into doing this later, but hasn't started yet, so he could probably use whatever you make as a jumping point.

**Comment by isaacsas** [comment]
@VitaminBrad Would it be tough to generate a `ModelingToolkit.ReactionSystem` directly?

**Comment by SiFTW** [comment]
> To elaborate a bit, I'm applying for a grant
Happy to provide a letter of support emphasising how enabling this would be. Best of luck!

**Comment by isaacsas** [comment]
We’ve got https://github.com/SciML/SBMLToolkit.jl now for SBML.
