### ISSUE TITLE
Make a documentation

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ReactionNetworkImporters.jl#84]
In order for this to be included in the SciMLDocs in the model importers section, it needs a documentation

**Comment by isaacsas** [comment]
👍

**Comment by isaacsas** [comment]
https://sciml.github.io/ReactionNetworkImporters.jl

Stable should hopefully build with the release I just tagged.

**Comment by isaacsas** [comment]
Let me know if there is a CNAME I should use or not. (Not sure it is needed given the docs currently mimic the README, but at some point we could improve them with a dynamic tutorial doc that actually loads and simulates something.)
